FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY internal ./internal
COPY cmd/cli-client ./cmd/cli-client

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/cli-client ./cmd/cli-client

FROM alpine:latest

WORKDIR /app

# Копируем бинарник из стадии сборки
COPY --from=builder /app/bin/cli-client .

ENTRYPOINT ["./cli-client"]
CMD ["--server=rabbitmq", "--channel=general"]
