services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - chat-net

  console-client:
    build:
      context: .
      dockerfile: console_client/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - chat-net

  gui-client:
    build:
      context: .
      dockerfile: gui_client/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - chat-net

networks:
  chat-net: {}