FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.* ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o cli-client ./main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/cli-client .
ENTRYPOINT ["./cli-client"]
CMD ["--host=rabbitmq", "general"]